# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 16:41
from __future__ import unicode_literals

from django.db import migrations


def initial_prices(apps, schema_editor):
    prices = [
        {'standard': ['Standard Plan', 50]},
    ]
    plan_price = apps.get_model('payments', 'PlanPrice')

    if plan_price.objects.all().count() == 0:
        for price in prices:
            for slug, val in price.items():
                plan_price.objects.create(slug=slug, name=val[0], price=val[1])


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('payments', '0002_planprice'),
    ]

    operations = [
        migrations.RunPython(initial_prices),
    ]
