# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='name',
        ),
    ]
