# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161127_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('0', 'Trial'), ('1', 'Standard'), ('2', 'Custom')], default='0', max_length=1),
        ),
    ]
