# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161201_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_widget_tip',
            field=models.BooleanField(default=True),
        ),
    ]
